In [1]:
d={"Fruits":["Banana","Orange","Apple","Grapes"],
   "Size":[23,30,40,50],
   "Weight":[80,60,70,40],
   "Color":["Yellow","Orange","Red","Green"]}

In [2]:
d

{'Fruits': ['Banana', 'Orange', 'Apple', 'Grapes'],
 'Size': [23, 30, 40, 50],
 'Weight': [80, 60, 70, 40],
 'Color': ['Yellow', 'Orange', 'Red', 'Green']}

In [3]:
import pandas as pd
df=pd.DataFrame(d)

In [4]:
df

   Fruits  Size  Weight   Color
0  Banana    23      80  Yellow
1  Orange    30      60  Orange
2   Apple    40      70     Red
3  Grapes    50      40   Green

In [5]:
df.describe()

            Size     Weight
count   4.000000   4.000000
mean   35.750000  62.500000
std    11.786291  17.078251
min    23.000000  40.000000
25%    28.250000  55.000000
50%    35.000000  65.000000
75%    42.500000  72.500000
max    50.000000  80.000000

In [6]:
x=10
if x==10:
    print("x is equal to 10")

x is equal to 10

In [8]:
x=10
if x>10:
    print("x is equal to 10")
else:
    print("x is not greater than 10")

x is not greater than 10

In [14]:
Age=18
if Age>=18:
    print("Person is  eligible for vote")
else:
    print("Person is not eligible for vote")

Person is  eligible for vote

In [18]:
("Person is  eligible for vot   printe")
else:C
    print("Person is not eligible for vote")

Enter the Age:=18
Person is  eligible for vote

In [19]:
x=int(input("Enter the First number:="))
y=int(input("Enter the Second number:="))
z=int(input("Enter the Third number:="))
if x>y and x>z:
    print("x is greatest among all")
elif y>z:
    print("y is greatest among all")
else:
    print("z is greatest amog all")

Enter the First number:=42
Enter the Second number:=80
Enter the Third number:=100
z is greatest amog all

In [ ]:
a=int(input("Enter the First number:="))
b=int(input("Enter the Second number:="))
c=int(input("Enter the Third number:="))
d=int(input("Enter the Forth number:="))
e=int(input("Enter the Fifth number:="))
if a>b and b>c and 
    print("x is greatest among all")
elif y>z:
    print("y is greatest among all")
else:
    print("z is greatest amog all")

In [20]:
x=100
if x>10:
    print("x is satisfied")
    if x>=50:
        print("sdjfjgh")
    else:
        print("jfbdjvfjdvhg")

x is satisfied
sdjfjgh